name: Validate Docker Build

on:
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  validate-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false  # Don't push, just build to validate
          tags: mcbenchmark/minecraft-builder-base:pr-validation
          cache-from: type=registry,ref=mcbenchmark/minecraft-builder-base:latest
          load: true   # Load the image into Docker engine

      - name: Test image existence
        run: docker image inspect mcbenchmark/minecraft-builder-base:pr-validation >/dev/null 2>&1
